name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    name: 🧹 Cleanup PR Preview Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          if [ -d "pr-${PR_NUMBER}" ]; then
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git rm -rf "pr-${PR_NUMBER}"
            git commit -m "🧹 Cleanup preview for PR #${PR_NUMBER}"
            git push origin gh-pages
            echo "Cleaned up preview for PR #${PR_NUMBER}"
          else
            echo "No preview directory found for PR #${PR_NUMBER}"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.pull_request.number }};

            const comment = `## 🧹 Preview Cleanup

            The preview deployment for this PR has been removed.

            ---
            📝 **PR #${prNumber}** closed
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
